# ROS 2 version of FixedArray.msg for rosidl_generator_eus test
float32[3] float32_data
float64[3] float64_data
int16[3] int16_data
int32[3] int32_data
int64[3] int64_data
int8[3] int8_data
uint16[3] uint16_data
uint32[3] uint32_data
uint64[3] uint64_data
uint8[17] uint8_data
bool[2] bool_data
builtin_interfaces/Time[2] time_data
builtin_interfaces/Duration[2] duration_data
std_msgs/String[2] string_data
